version = 1

test_patterns = [
  "test_*.py",
  "*_test.py",
  "conftest.py"
]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = ["requirements.txt"]

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 120
